---
title: "Regulatory Analysis"
author: "Andrew Burr"
date: "January 26, 2017"
output: html_document
---



```{r setup, include=FALSE}
source('global.R')
#force R to not use scientific notation
options(scipen=999)


```



*Alignment Analysis*

Below are the code chunks for analyzing the alignments gathered between each piRNA and the targeting sequences.



```{r coexpression_setup}



# load the targeting sequences expressions
voom_sRNA <- read.table(file = "../../data_files/stem_diff_targeting/targeting_sRNA.csv",
                        stringsAsFactors = F, 
                        header  = T, 
                        sep = ",")
rmsk <- read.table(file = "../../data_files/stem_diff_alignments/small_sa_og_norRNA_25_33_25bp_alignments_repeatmasker.txt",
                   stringsAsFactors = F,
                   header  = F,
                   sep = "\t")
rmsk <- rmsk[!grepl(rmsk$V3, pattern = "tRNA"),]
voom_sRNA <- voom_sRNA[!(voom_sRNA$sRNA %in% rmsk$V1),]
voom_top <- read.table(file = "../../data_files/stem_diff_targeting/top_targeting_sRNA.csv", 
                       stringsAsFactors = F,
                       header  = T, 
                       sep = ",")


#load in the gene expression from RNA seq experiment
gene_expression <- read.csv(file = "../../data_files/RNAseq_expressed_genes/GSC_vs_nonGSC_all_differentially_expressed_genes.csv", 
                            sep = ",", 
                            stringsAsFactors = F)
top_genes <- read.csv(file = "../../data_files/RNAseq_expressed_genes/GSC_vs_nonGSC_top_pval05_differentially_expressed_genes.csv", 
                      sep = ",",
                      stringsAsFactors = F)



UTR_alignments <- list()
UTR_alignments[[1]] <-  read.delim("../../data_files/stem_diff_alignments/temp_alignments/3UTR_temp_alignments_bt2v1score2.txt", header=FALSE, stringsAsFactors=FALSE)[,]
UTR_alignments[[2]] <-  read.delim("../../data_files/stem_diff_alignments/temp_alignments/3UTR_temp_alignments_bt2v1score4.txt", header=FALSE, stringsAsFactors=FALSE)[,]
UTR_alignments[[3]] <-  read.delim("../../data_files/stem_diff_alignments/temp_alignments/3UTR_temp_alignments_bt2v1score6.txt", header=FALSE, stringsAsFactors=FALSE)[,]
UTR_alignments_names <- c("bt2v1score2", "bt2v1score4" , "bt2v1score6")




cDNA_alignments <- list()
cDNA_alignments[[1]] <-  read.delim("../../data_files/stem_diff_alignments/temp_alignments/cDNA_temp_alignments_bt2v1score2.txt", header=FALSE, stringsAsFactors=FALSE)[,]
cDNA_alignments[[2]] <-  read.delim("../../data_files/stem_diff_alignments/temp_alignments/cDNA_temp_alignments_bt2v1score4.txt", header=FALSE, stringsAsFactors=FALSE)[,]
cDNA_alignments[[3]] <-  read.delim("../../data_files/stem_diff_alignments/temp_alignments/cDNA_temp_alignments_bt2v1score6.txt", header=FALSE, stringsAsFactors=FALSE)[,]


# WHERE ARE THESE?!?!?!!??!?!?!
# 
# gsgarahd
# sfhsd
# sghfg
# sgsh
# sghshhsrhjsytu
# sgsgs
# liujkh;lkugs

promoter_alignments <- list()
promoter_alignments[[1]] <-  read.delim("../../data_files/stem_diff_alignments/temp_alignments/promoter_temp_alignments_bt2v1score2.txt", header=FALSE, stringsAsFactors=FALSE)[,]
promoter_alignments[[2]] <-  read.delim("../../data_files/stem_diff_alignments/temp_alignments/promoter_temp_alignments_bt2v1score4.txt", header=FALSE, stringsAsFactors=FALSE)[,]
promoter_alignments[[3]] <-  read.delim("../../data_files/stem_diff_alignments/temp_alignments/promoter_temp_alignments_bt2v1score6.txt", header=FALSE, stringsAsFactors=FALSE)[,]
promoter_alignments_names <- c("bt2v1score2", "bt2v1score4" , "bt2v1score6")


```



```{r build plot function}


alignments <- UTR_alignments[[1]]
colnames(alignments) <- c("piRNA", "transcript_id", "bp_start", "alignment_info", "mismatches")
# remove the transcipt name
alignments$transcript_id <- sapply(alignments$transcript_id,
                                   FUN = function(x){unlist(strsplit(x, split = "\\|"))[2]})

conversion <- read.table(file =  "../../conversion_sets/ensembl_conversion.txt",
                         header = T, 
                         stringsAsFactors = F,
                         sep = "\t")

alignments <- merge(alignments, 
                    conversion, 
                    by = "transcript_id")
alignments <- subset(alignments, select = c(piRNA, hgnc_symbol))
alignments <- unique(alignments)
#alignments <- alignmentInfo(alignments)

piRNA_expression <- subset(x = voom_sRNA, 
                          select = c(sRNA, logFC, adj.P.Val))
colnames(piRNA_expression) <- c("piRNA", "piRNA_logFC", "piRNA_pval")       


coexpression <- buildCoexpression(alignments = alignments, 
                                  piRNA_expression = piRNA_expression, 
                                  gene_expression = gene_expression)

coexpressionPlot(coexpression)

```



**3UTR**


```{r 3UTR_alignments, echo = FALSE}



# load the targeting sequences expressions
piRNA.expression <- read.table(file = "../../data_files/stem_diff_targeting/targeting_sRNA.csv",
                        stringsAsFactors = F, 
                        header  = T, 
                        sep = ",")
piRNA.expression <- subset(x = voom_sRNA, 
                          select = c(sRNA, logFC, adj.P.Val))
colnames(piRNA.expression) <- c("piRNA", "piRNA_logFC", "piRNA_pval")  


# 
# 
# rmsk <- read.table(file = "../../data_files/stem_diff_alignments/small_sa_og_norRNA_25_33_25bp_alignments_repeatmasker.txt",
#                    stringsAsFactors = F,
#                    header  = F,
#                    sep = "\t")
# rmsk <- rmsk[!grepl(rmsk$V3, pattern = "tRNA"),]
# voom_sRNA <- voom_sRNA[!(voom_sRNA$sRNA %in% rmsk$V1),]

top.piRNA <- read.table(file = "../../data_files/stem_diff_targeting/top_targeting_sRNA.csv", 
                       stringsAsFactors = F,
                       header  = T, 
                       sep = ",")

#load in the gene expression from RNA seq experiment
gene.expression <- read.csv(file = "../../data_files/RNAseq_expressed_genes/GSC_vs_nonGSC_all_differentially_expressed_genes.csv", 
                            sep = ",", 
                            stringsAsFactors = F)

gene.expression <- subset(gene_expression, 
                          select = c(hgnc_symbol, logFC, adj.P.Val))
colnames(gene.expression) <- c("gene", "gene_logFC", "gene_pval")  

top_genes <- read.csv(file = "../../data_files/RNAseq_expressed_genes/GSC_vs_nonGSC_top_pval05_differentially_expressed_genes.csv", 
                      sep = ",",
                      stringsAsFactors = F)


alignments <- list()
alignments[[1]] <-  read.delim("../../data_files/stem_diff_alignments/temp_alignments/3UTR_temp_alignments_bt2v1score2.txt", header=FALSE, stringsAsFactors=FALSE)[,]
alignments[[2]] <-  read.delim("../../data_files/stem_diff_alignments/temp_alignments/3UTR_temp_alignments_bt2v1score4.txt", header=FALSE, stringsAsFactors=FALSE)[,]
alignments[[3]] <-  read.delim("../../data_files/stem_diff_alignments/temp_alignments/3UTR_temp_alignments_bt2v1score6.txt", header=FALSE, stringsAsFactors=FALSE)[,]
alignments_names <- c("bt2v1score2", "bt2v1score4" , "bt2v1score6")

conversion <- read.table(file =  "../../conversion_sets/ensembl_conversion.txt",
                         header = T, 
                         stringsAsFactors = F,
                         sep = "\t")

for(n in 1:length(alignments)){
  temp <- alignments[[n]]
  colnames(temp) <- c("piRNA", "transcript_id", "bp_start", "alignment_info", "mismatches")
  # remove the transcipt name
  temp$transcript_id <- sapply(temp$transcript_id,
                                     FUN = function(x){unlist(strsplit(x, split = "\\|"))[2]})
  
  temp <- merge(temp, 
                conversion, 
                by = "transcript_id")
  temp <- subset(temp, 
                 select = c(piRNA, hgnc_symbol))
  temp <- unique(temp)
  colnames(temp) <- c("piRNA", "gene")
  alignments[[n]] <- temp
}





for (alignments in alignments){
coexpression <- buildCoexpression(alignments = alignments , 
                                  piRNA.expression = piRNA.expression, 
                                  gene.expression = gene.expression)

coexpressionPlot(coexpression)
}

#loading in the bowtie alignments from piRNA against cDNA
#alignments <- read.delim("../alignments/targeting_alignments/cDNA/sa_og_norRNA_25_33_noncRNA_21bp_list_alignments_3UTR_v3.txt", header=FALSE, stringsAsFactors=FALSE)[,]

#system("grep -f temp_read_names.txt ../alignments/list_targeting/small_sa_og_norRNA_25_33_25bp_targeting_3UTR_51_l9_n0_e140.txt > 3UTR_temp_alignments.txt" )

#alignments <- read.delim("3UTR_temp_alignments.txt", header=FALSE, stringsAsFactors=FALSE)[,]
#label the columns approriately
#colnames(alignments) <- c("piRNA", "gene", "bp_start", "mismatches")


for(alignments_number in 1:length(UTR_alignments)){
  
  alignments <- as.data.frame(UTR_alignments[[alignments_number]])
  name <- UTR_alignments_names[alignments_number]
  
  colnames(alignments) <- c("piRNA", "transcript_id", "bp_start", "alignment_info", "mismatches")
  #alignments$transcript_id <- gsub(pattern = "\\..*", replacement = "", alignments$transcript_id)
  alignments$transcript_id <- sapply(alignments$transcript_id,
                                     FUN = function(x){unlist(strsplit(x, split = "\\|"))[2]})
  
  conversion <- read.table(file =  "../../conversion_sets/ensembl_conversion.txt",
                           header = T, 
                           stringsAsFactors = F,
                           sep = "\t")

  alignments <- merge(alignments, 
                      conversion, 
                      by = "transcript_id" )
  alignments <- unique(alignments)
  alignments <- alignmentInfo(alignments)
  
  #alignments <- alignments[alignments$targets < 20,]
  
  
  
  coexpression <- 
    unique(
      merge(subset(voom_sRNA, 
                   select = c(sRNA, logFC, adj.P.Val)),
            subset(alignments, 
                   select = c(piRNA, hgnc_symbol)),
            by.x = "sRNA", by.y = "piRNA"))
  
  colnames(coexpression)[1:3] <- c("piRNA", "piRNA_logFC", "piRNA_pval")
  coexpression <-merge(x = coexpression,
                       y = subset(gene_expression, 
                                  select = c(hgnc_symbol, logFC, adj.P.Val)),
                       by = "hgnc_symbol")
  colnames(coexpression)[5:6] <- c( "gene_logFC", "gene_pval")
  
  
  
  write.table(x = coexpression,
              file =  paste("../../data_files/coexpressions/3UTR_coexpression_", name ,".csv"),
              quote = F,
              sep = ",",
              row.names = F)
  
  
  # create and save the coexpression plot
  pdf(file =  paste("../../figures/3UTR_coexpression_",name ,".pdf"), 6,4)
  print(
    
    #create the correlation plot 
    ggplot(data = coexpression, aes(y = gene_logFC, 
                                    x = piRNA_logFC)) +
      # geom_rect(aes(xmin = 2, xmax =ceiling(max(coexpression$piRNA_logFC)), ymax = -2, ymin = floor(min(coexpression$gene_logFC))), fill = "white", color = "blue", alpha = 1/20000, size = .7) + 
      # geom_rect(aes(xmax = -2, xmin = floor(min(coexpression$piRNA_logFC)), ymin = 2, ymax = ceiling(max(coexpression$gene_logFC))),fill = "white", color = "blue", alpha = 1/20000, size = .7) + 
      geom_point(aes(color = gene_pval, 
                     y = gene_logFC,
                     x = piRNA_logFC, 
                     alpha = 1-piRNA_pval), 
                 size = .9) +
      scale_color_gradientn(name ="Gene Pval" , 
                            colors = c("darkblue","lightblue","red"),
                            breaks = c( .01,.1,1), 
                            limits = c(0,1), 
                            values = c(.0000001, .1, 1)) +
      scale_alpha_continuous(labels = c(1,.1,.05,.001), 
                             limits = c(.001,  1),
                             breaks = c( .001,.05,.1,1),
                             name = "piRNA Pval") + 
      geom_hline(aes(yintercept = 2), 
                 linetype ="dotted") +
      geom_hline(aes(yintercept = -2), 
                 linetype = "dotted") +
      geom_vline(aes(xintercept = 2), 
                 linetype ="dotted") +
      geom_vline(aes(xintercept = -2), 
                 linetype ="dotted") +
      scale_y_continuous(breaks = c(seq((floor(min(coexpression$gene_logFC))), ceiling(max(coexpression$gene_logFC)), 1))) +
      scale_x_continuous(breaks = c(seq((floor(min(coexpression$piRNA_logFC))), ceiling(max(coexpression$piRNA_logFC)), 1))) +
      #scale_linetype_manual(guide = FALSE) +
      
      guides(linetype = FALSE) +   
      #ggtitle("3UTR Targeting: Gene LFC ~ piRNA LFC ") +
      #scale_color_manual(values = c("black", "blue")) + 
      xlab("piRNA logFC") +
      ylab("Target logFC") +
      #scale_size(range =c(.5,1.5)) + 
      # labs(  color = "Gene Pval") +
      theme_bw() 
      #theme(panel.grid.major.x = element_blank()) 
      #theme(legend.position ="right")
    
    
  )
  dev.off()
}

```




**cDNA**


```{r cDNA_alignments, echo = FALSE}


# file to convert ensembl gene ID to gene name
conversion <- read.table(file =  "../../conversion_sets/ensembl_conversion.txt",
                         header = T,
                         stringsAsFactors = F, 
                         sep = "\t")
#top_genes <- read.csv("../../RNAseq/data/StemVsDiff_top_DE_genes.txt", stringsAsFactors=FALSE)[,c(1,2,8)]
alignments_names <- c("gene_bt2v1score2", "gene_bt2v1score4" , "gene_bt2v1score6", "gene_bt2v1score8", "gene_bt2v1score10")
gene_expression <- read.csv(file = "../../data_files/RNAseq_expressed_genes/GSC_vs_nonGSC_all_differentially_expressed_genes.csv",
                            stringsAsFactors = F)

# convert the names of the genes
gene_expression <- 
  unique(
    merge(conversion[,c(1,3)],
          gene_expression, 
          by.x = "gene_id",
          by.y = "row.names")
  )

for(alignments_number in 1:length(cDNA_alignments)){
  # load in the alignments
  alignments <- as.data.frame(cDNA_alignments[[alignments_number]])
  name <- alignments_names[alignments_number]
  
  colnames(alignments) <- c("piRNA", "transcript_id", "bp_start", "alignment_info", "mismatches")
  # remove the ".#" descriptor (not needed) from transcript ID
  alignments$transcript_id <- gsub(pattern = "\\..*",
                                   replacement = "", 
                                   alignments$transcript_id)
  # convert the ID to the gene name
  alignments <- merge(x = alignments, 
                      y = conversion, 
                      by = "transcript_id" )
  # select only unique gene alignments
  alignments <- unique(alignments)
  
  #split the alignment reference name into the appropraite columns
  #alignments$hgnc_symbol <- sapply(alignments$gene, FUN = function(x){unlist(strsplit(x, split = " "))[4]})
  #alignments$transcript <- sapply(alignments$gene, FUN = function(x){unlist(strsplit(x, split = " "))[1]})
  #alignments$length <- sapply(alignments$gene, FUN = function(x){unlist(strsplit(x, split = " "))[5]})
  #alignments$length <-  as.numeric(sapply(alignments$length, sub, pattern =  "transcript_length:", replacement =  ""))
  
  #generate alignment info
  alignments <- alignmentInfo(alignments)
  
  
  #alignments <- alignments[alignments$targets < 20,]
  
  
  #create the coexpression table
  coexpression <-
    unique(
      merge(
        subset(x = voom_sRNA,
               select = c(sRNA, logFC, adj.P.Val)),
        subset(x = alignments, 
               select = c(piRNA, hgnc_symbol)),
        by.x = "sRNA",
        by.y = "piRNA"))
  
  colnames(coexpression)[1:3] <- c("piRNA", "piRNA_logFC", "piRNA_pval")
  coexpression <-merge(x = coexpression,
                       y = subset(gene_expression, 
                              select = c(hgnc_symbol, logFC, adj.P.Val)),
                       by = "hgnc_symbol")
  colnames(coexpression)[5:6] <- c( "gene_logFC", "gene_pval")
  # save the coexpressions to data directory
  write.table(x = coexpression, 
              file =  paste("../../data_files/coexpressions/cDNA_coexpression_", name ,".csv"),
              quote = F,
              sep = ",", 
              row.names = F)
  # write the plot to figures directory
  pdf(paste("../../figures/cDNA_coexpression_",name ,".pdf"), 6,4)
  print(
    
    ggplot(data = coexpression,aes( y = gene_logFC, 
                                    x = piRNA_logFC)) +
      #geom_rect(aes(xmin = 2, xmax =ceiling(max(coexpression$piRNA_logFC)), ymax = -2, ymin = floor(min(coexpression$gene_logFC))), fill = "white", color = "blue", alpha = 1/20000, size = .7) + 
      #geom_rect(aes(xmax = -2, xmin = floor(min(coexpression$piRNA_logFC)), ymin = 2, ymax = ceiling(max(coexpression$gene_logFC))),fill = "white", color = "blue", alpha = 1/20000, size = .7) + 
      geom_point(aes(color = gene_pval, 
                     y = gene_logFC,
                     x = piRNA_logFC, 
                     alpha = 1-piRNA_pval), 
                 size = .9) +
      scale_color_gradientn(name ="Gene Pval" , 
                            colors = c("darkblue","lightblue","red"),
                            breaks = c( .01,.1,1),
                            limits = c(0,1), 
                            values = c(.0000001, .1, 1)) +
      scale_alpha_continuous(labels = c(1,.1,.05,.001), 
                             limits = c(.001,  1), 
                             breaks = c( .001,.05,.1,1), 
                             name = "piRNA Pval") + 
      geom_hline(aes(yintercept = 2), 
                 linetype ="dotted") +
      geom_hline(aes(yintercept = -2), 
                 linetype = "dotted") +
      geom_vline(aes(xintercept = 2), 
                 linetype ="dotted") +
      geom_vline(aes(xintercept = -2), 
                 linetype ="dotted") +
      scale_y_continuous(breaks = c(seq((floor(min(coexpression$gene_logFC))), ceiling(max(coexpression$gene_logFC)), 1))) +
      scale_x_continuous(breaks = c(seq((floor(min(coexpression$piRNA_logFC))), ceiling(max(coexpression$piRNA_logFC)), 1))) +
      #scale_linetype_manual(guide = FALSE) +
      
      guides(linetype = FALSE) +   
      #ggtitle("mRNA Targeting: Gene LFC ~ piRNA LFC ") +
      #scale_color_manual(values = c("black", "blue")) + 
      xlab("piRNA logFC") +
      ylab("Target logFC") +
      #scale_size(range =c(.5,1.5)) + 
      # labs(  color = "Gene Pval") +
      theme_bw() 
      #theme(panel.grid.major.x = element_blank()) +
      #theme(legend.position ="none")
    

  )
  dev.off()
}

gene_expression <- read.csv(file =  "../../data_files/RNAseq_expressed_genes/GSC_vs_nonGSC_all_differentially_expressed_transcripts.csv",
                            stringsAsFactors = F)
top_genes <- read.csv(file = "../../data_files/RNAseq_expressed_genes/GSC_vs_nonGSC_top_pval05_differentially_expressed_transcripts.csv", 
                      stringsAsFactors=FALSE)[,c(1,2,8)]
alignments_names <- c("transcript_bt2v1score2", "transcript_bt2v1score4" , "transcript_bt2v1score6")




for(alignments_number in 1:length(cDNA_alignments)){
  
  alignments <- as.data.frame(cDNA_alignments[[alignments_number]])
  name <- alignments_names[alignments_number]
  
  colnames(alignments) <- c("piRNA", "transcript_id", "bp_start", "alignment_info", "mismatches")
  alignments$transcript_id <- gsub(pattern = "\\..*", 
                                   replacement = "", 
                                   alignments$transcript_id)
  
  alignments <- merge(alignments, 
                      conversion, 
                      by = "transcript_id" )
  
  alignments <- unique(alignments)
  
  #split the alignment reference name into the appropraite columns
  #alignments$hgnc_symbol <- sapply(alignments$gene, FUN = function(x){unlist(strsplit(x, split = " "))[4]})
  #alignments$transcript <- sapply(alignments$gene, FUN = function(x){unlist(strsplit(x, split = " "))[1]})
  #alignments$length <- sapply(alignments$gene, FUN = function(x){unlist(strsplit(x, split = " "))[5]})
  #alignments$length <-  as.numeric(sapply(alignments$length, sub, pattern =  "transcript_length:", replacement =  ""))
  
  #generate alignment info
  alignments <- alignmentInfo(alignments)
  
  
  #alignments <- alignments[alignments$targets < 20,]
  
  
  #create the coexpression table
  coexpression <- unique(merge(subset(voom_sRNA, select = c(sRNA, logFC, adj.P.Val)),
                               subset(alignments, select = c(piRNA, hgnc_symbol,transcript_id)),
                               by.x = "sRNA", by.y = "piRNA"))
  colnames(coexpression)[1:3] <- c("piRNA", "piRNA_logFC", "piRNA_pval")
  coexpression <-merge(coexpression,
                       subset(x = gene_expression,
                              select = c(transcript_id, logFC, adj.P.Val)),
                       by = "transcript_id")
  colnames(coexpression)[6:7] <- c( "gene_logFC", "gene_pval")
  
 write.table(x = coexpression, 
             file = paste("../../data_files/coexpressions/cDNA_coexpression_", name ,".csv"),
             quote = F, 
             sep = ",",
             row.names = F)
  
  pdf(paste("../../figures/cDNA_coexpression_",name ,".pdf"), 6,4)
  print(
    
    ggplot(data = coexpression,aes(y = gene_logFC, 
                                   x = piRNA_logFC)) +
      #geom_rect(aes(xmin = 2, xmax =ceiling(max(coexpression$piRNA_logFC)), ymax = -2, ymin = floor(min(coexpression$gene_logFC))), fill = "white", color = "blue", alpha = 1/20000, size = .7) + 
      #geom_rect(aes(xmax = -2, xmin = floor(min(coexpression$piRNA_logFC)), ymin = 2, ymax = ceiling(max(coexpression$gene_logFC))),fill = "white", color = "blue", alpha = 1/20000, size = .7) + 
      geom_point(aes(color = gene_pval, 
                     y = gene_logFC, 
                     x = piRNA_logFC, 
                     alpha = 1-piRNA_pval), 
                 size = .9) +
      scale_color_gradientn(name ="Gene Pval" ,
                            colors = c("darkblue", "lightblue", "red"),
                            breaks = c(.01, .1, 1), 
                            limits = c(0, 1),
                            values = c(.0000001, .1, 1)) +
      scale_alpha_continuous( labels = c(1,.1,.05,.001),
                              limits = c(.001, 1),
                              breaks = c(.001, .05, .1, 1), 
                              name = "piRNA Pval") + 
      geom_hline(aes(yintercept = 2), 
                 linetype ="dotted") +
      geom_hline(aes(yintercept = -2), 
                 linetype = "dotted") +
      geom_vline(aes(xintercept = 2), 
                 linetype ="dotted") +
      geom_vline(aes(xintercept = -2), 
                 linetype ="dotted") +
      scale_y_continuous(breaks = c(seq((floor(min(coexpression$gene_logFC))), ceiling(max(coexpression$gene_logFC)), 1))) +
      scale_x_continuous(breaks = c(seq((floor(min(coexpression$piRNA_logFC))), ceiling(max(coexpression$piRNA_logFC)), 1))) +
      #scale_linetype_manual(guide = FALSE) +
      
      guides(linetype = FALSE) +  
      #ggtitle("mRNA Targeting: Isoform LFC ~ piRNA LFC ") +
      #scale_color_manual(values = c("black", "blue")) + 
      xlab("piRNA logFC") +
      ylab("Target logFC") +
      #scale_size(range =c(.5,1.5)) + 
      # labs(  color = "Gene Pval") +
      theme_bw() 
      #theme(panel.grid.major.x = element_blank()) +
      #theme(legend.position ="none")
    

  )
  dev.off()
  
  
}


```





**Promoter**

```{r promotor_alignments, echo = FALSE}

#conversion table for converting RefSeq ids to HGNC gene symbols
conversion <- read.delim(file = "../../conversion_sets/hgnc_to_refseq.txt",
                         stringsAsFactors=FALSE, sep = "\t")
colnames(conversion) <- c("hgnc_symbol", "refseq_id")



for(alignments_number in 1:length(promoter_alignments)){
  
  alignments <- as.data.frame(promoter_alignments[[alignments_number]])
  name <- promoter_alignments_names[alignments_number]
  
  colnames(alignments) <- c("piRNA", "refseq_id", "bp_start", "alignment_info", "mismatches")
  #alignments$transcript_id <- gsub(pattern = "\\..*", replacement = "", alignments$transcript_id)
  
  alignments <- merge(alignments, 
                      conversion, 
                      by = "refseq_id")
  alignments <- unique(alignments)
  
  #finding total targets for each piRNA
  target_number <- 
    as.data.frame(
      table(
        unique(
          subset(x = alignments, 
                 select = c(piRNA,hgnc_symbol)
          )
        )[,1]
      )
    )
  colnames(target_number) <- c("piRNA", "targets")
  alignments <- merge(alignments, target_number, by = "piRNA")
  
  #find total time gene is targeted by unique piRNA
  target_number <-
    as.data.frame(
      table(
        unique(
          subset(x = alignments, 
                 select = c(piRNA,hgnc_symbol)
          )
        )[,2]
      )
    )
  
  
  colnames(target_number) <- c("hgnc_symbol", "gene_frequency")
  alignments <- merge(alignments,
                      target_number,
                      by = "hgnc_symbol")
  
  
  #create the coexpression table
  coexpression <- 
    unique(
      merge(
        subset(x = voom_sRNA, 
               select = c(sRNA, logFC, adj.P.Val)
        ),
        subset(x = alignments,
               select = c(piRNA, hgnc_symbol)
        ),
        by.x = "sRNA",
        by.y = "piRNA")
    )
  
  
  colnames(coexpression)[1:3] <- c("piRNA", "piRNA_logFC", "piRNA_pval")
  coexpression <- merge(coexpression,
                        subset(x = gene_expression, 
                               select = c(hgnc_symbol, logFC, adj.P.Val)
                        ),
                        by = "hgnc_symbol")
  colnames(coexpression)[5:6] <- c( "gene_logFC", "gene_pval")
  
  write.table(x = coexpression,
              paste("../../data_files/coexpressions/promoter_coexpression_", name ,".csv"),
              quote = F, 
              sep = ",",
              row.names = F)
  
  pdf(paste("../../figures/promoter_coexpression_",name ,".pdf"), 6,4)
  print(
    #plot of the correlatiosn between expression data
    ggplot(data = coexpression, 
           aes(y = gene_logFC, 
               x = piRNA_logFC)) +
      # geom_rect(aes(xmin = 2, xmax =ceiling(max(coexpression$piRNA_logFC)), ymax = -2, ymin = floor(min(coexpression$gene_logFC))), fill = "white", color = "blue", alpha = 1/20000, size = .7) + 
      #geom_rect(aes(xmax = -2, xmin = floor(min(coexpression$piRNA_logFC)), ymin = 2, ymax = ceiling(max(coexpression$gene_logFC))),fill = "white", color = "blue", alpha = 1/20000, size = .7) + 
      geom_point(aes(color = gene_pval, 
                     y = gene_logFC, 
                     x = piRNA_logFC, 
                     alpha = 1-piRNA_pval), 
                 size = .9) +
      scale_color_gradientn(name ="Gene Pval" , 
                            colors = c("darkblue","lightblue","red"),
                            breaks = c( .01,.1,1), 
                            limits = c(0,1), 
                            values = c(.0000001, .1, 1)) +
      scale_alpha_continuous(labels = c(1,.1,.05,.001),
                             limits = c(.001,  1), 
                             breaks = c( .001,.05,.1,1), 
                             name = "piRNA Pval") + 
      geom_hline(aes(yintercept = 2), 
                 linetype ="dotted") +
      geom_hline(aes(yintercept = -2),
                 linetype = "dotted") +
      geom_vline(aes(xintercept = 2),
                 linetype ="dotted") +
      geom_vline(aes(xintercept = -2),
                 linetype ="dotted") +
      scale_y_continuous(breaks = c(seq((floor(min(coexpression$gene_logFC))), ceiling(max(coexpression$gene_logFC)), 1))) +
      scale_x_continuous(breaks = c(seq((floor(min(coexpression$piRNA_logFC))), ceiling(max(coexpression$piRNA_logFC)), 1))) +
      #scale_linetype_manual(guide = FALSE) +
      
      guides(linetype = FALSE) +   
      #ggtitle("Promoter Region Targeting: Gene LFC ~ piRNA LFC ") +
      #scale_color_manual(values = c("black", "blue")) + 
      xlab("piRNA LFC") +
      ylab("Target LFC") +
      #scale_size(range =c(.5,1.5)) + 
      # labs(  color = "Gene Pval") +
      theme_bw() 
    #theme(panel.grid.major.x = element_blank()) +
    #   theme(legend.position ="none")
  )
  dev.off()
}



```
