
# Load libraries
library(knitr)
library(edgeR)
library(biomaRt)
library(ggplot2)
library(beadarray)
library(limma)
library(illuminaHumanv4.db)
library("simpleaffy")
library("affyQCReport")
library(annotate)
require(reshape)
require('fgsea')
require(data.table)
require('KEGG.db')
require(ArrayTools)
require(CePa)

source('microarray_functions.R')
#source('FGSEA.R')
